name: Build Mac Mini EFI
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install -r requirements.txt
      - name: Build EFI for Mac Mini 2012
        run: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 OpenCore-Patcher-GUI.command --build --model Macmini6,2
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacMini-EFI
          path: /Users/runner/work/OCLP-macmini/OCLP-macmini/Build-Folder/OpenCore-Build
